tlm-adjoint/tlm_adjoint

python/tlm_adjoint/optimization.py
Call scipy.optimize.minimize only on process zero, some extra defensive programming
=> minimize scipy updates

python/tlm_adjoint/equations.py, python/tlm_adjoint_fenics/backend_code_generator_interface.py, python/tlm_adjoint_firedrake/backend_code_generator_interface.py
=> Do not return the matrix from assemble_linear_solver

tests/fenics/test_manager.py, tests/firedrake/test_manager.py, tests/numpy/test_manager.py
In test_Referrers_FixedPointEquation tests
=> Remove initial condition dependencies from NewtonIterationSolver

docs/manual.tex, python/tlm_adjoint/base_equations.py
Also simplify storage of non-linear dependencies.
=> Bugfix to Equation constructor when nl_deps is not supplied

docs/manual.tex, python/tlm_adjoint/eigendecomposition.py, python/tlm_adjoint/functions.py, python/tlm_adjoint_fenics/backend.py, python/tlm_adjoint_fenics/backend_interface.py, python/tlm_adjoint_firedrake/backend_interface.py, python/tlm_adjoint_numpy/backend_interface.py
Also adds extra type and shape checking when copying data in and out of functions and PETSc Vec objects
=> Updates to eigendecomposition module

docs/manual.tex, python/tlm_adjoint_fenics/backend.py, python/tlm_adjoint_fenics/fenics_equations.py, python/tlm_adjoint_firedrake/firedrake_equations.py, tests/fenics/test_base.py, tests/fenics/test_equations.py, tests/firedrake/test_equations.py
Addresses issue #34, supersedes pull request #33
=> Allow for different ghost modes / overlap types in interpolation

tests/fenics/test_models.py, tests/firedrake/test_models.py, tlm_adjoint/hessian.py, tlm_adjoint/optimization.py, tlm_adjoint/tlm_adjoint.py, tlm_adjoint/verification.py
Controls are now defined using functions (only).
=> Add DeprecationWarning to Control and EquationManager.find_initial_condition

tlm_adjoint/_code_generator/functions.py, tlm_adjoint/fenics/backend_interface.py, tlm_adjoint/firedrake/backend_interface.py, tlm_adjoint/interface.py, tlm_adjoint/numpy/backend_interface.py, tlm_adjoint/tlm_adjoint.py
Also add default FunctionInterface._new_tangent_linear
=> Rename function_tangent_linear to function_new_tangent_linear

examples/firedrake/manual/diffusion_adjoint.py, tests/fenics/test_base.py, tests/fenics/test_caches.py, tests/fenics/test_eigendecomposition.py, tests/fenics/test_equations.py, tests/fenics/test_examples.py, tests/fenics/test_gauss_newton.py, tests/fenics/test_manager.py, tests/fenics/test_minimize.py, tests/fenics/test_models.py, tests/fenics/test_overrides.py, tests/firedrake/test_base.py, tests/firedrake/test_caches.py, tests/firedrake/test_eigendecomposition.py, tests/firedrake/test_equations.py, tests/firedrake/test_examples.py, tests/firedrake/test_gauss_newton.py, tests/firedrake/test_interface.py, tests/firedrake/test_manager.py, tests/firedrake/test_minimize.py, tests/firedrake/test_models.py, tests/firedrake/test_overrides.py, tlm_adjoint/eigendecomposition.py, tlm_adjoint/equations.py, tlm_adjoint/firedrake/backend_interface.py, tlm_adjoint/hessian.py, tlm_adjoint/hessian_optimization.py, tlm_adjoint/verification.py
- Updates for complex Firedrake
- Use seed_test decorator
=> Updates to FEniCS and Firedrake tests

tests/fenics/test_models.py, tests/firedrake/test_models.py
Use more general perturbation directions in Taylor tests for test_oscillator and test_diffusion_1d_timestepping
=> test_models updates

tests/fenics/test_gauss_newton.py, tests/firedrake/test_gauss_newton.py, tlm_adjoint/hessian.py
Now require the caller to apply necessary complex conjugation
=> Gauss-Newton API change for complex case

tests/fenics/test_eigendecomposition.py, tests/firedrake/test_eigendecomposition.py, tlm_adjoint/eigendecomposition.py
Also use matrix free in test_HEP and test_NHEP, and add some basic eigenvalue tests.
=> eigendecompose API change: Require A_action to return the complex conjugate of the matrix action

docs/manual.tex, tests/fenics/test_eigendecomposition.py, tests/firedrake/test_eigendecomposition.py, tlm_adjoint/eigendecomposition.py
Also
- Make most `eigendecompose` arguments keyword only
- Update `eigendecompose` documentation
- Verify imaginary components of eigenvalues in `test_CachedHessian`
=> eigendecompose API change: Change B_matrix to B_action

docs/manual.tex, tests/numpy/test_base.py, tlm_adjoint/_code_generator/functions.py, tlm_adjoint/equations.py, tlm_adjoint/fenics/backend_interface.py, tlm_adjoint/firedrake/backend_interface.py, tlm_adjoint/interface.py, tlm_adjoint/numpy/backend_interface.py, tlm_adjoint/numpy/equations.py
Also remove deprecated tangent-linear function and methods.
=> Make some arguments keyword only

tlm_adjoint/equations.py
Simplifies the definition of a class of convergence criteria norms
=> Add CustomNormsFixedPointSolver

tlm_adjoint/equations.py
Fixes tangent-linear fixed-point norms. Also fix a complex corner-case with custom norms.
=> Remove CustomNormsFixedPointSolver, move functionality into FixedPointSolver

tlm_adjoint/checkpointing.py, tlm_adjoint/tlm_adjoint.py
Also
- Remove default values for `CheckpointStorage` constructor arguments `store_ics` and `store_data`.
- Delete checkpoint files when `Checkpoints` objects are destroyed.
- Minor updates to `ReplayStorage`.
=> Move checkpointing code into tlm_adjoint/checkpoints.py

docs/manual.tex, tests/fenics/test_base.py, tests/firedrake/test_base.py, tests/numpy/test_base.py, tlm_adjoint/binomial_checkpointing.py, tlm_adjoint/checkpointing.py, tlm_adjoint/hessian_optimization.py, tlm_adjoint/manager.py, tlm_adjoint/optimization.py, tlm_adjoint/tlm_adjoint.py
Use `CheckpointingManager` classes to control checkpointing
=> Refactor checkpointing code

setup.py, tlm_adjoint/_code_generator/functions.py, tlm_adjoint/fenics/backend_interface.py, tlm_adjoint/firedrake/backend_interface.py, tlm_adjoint/interface.py, tlm_adjoint/numpy/backend_interface.py
- Use positional-only arguments.
- Bugfix to space type checking.
=> function_axpy updates

docs/manual.tex, tests/fenics/test_manager.py, tests/firedrake/test_manager.py, tests/numpy/test_manager.py, tlm_adjoint/checkpointing.py, tlm_adjoint/equations.py, tlm_adjoint/manager.py, tlm_adjoint/tlm_adjoint.py
When rerunning the forward, and by default, recompute non-linear dependencies of equations with an active adjoint.
=> Forward replay activity analysis

tlm_adjoint/binomial_checkpointing.py, tlm_adjoint/checkpointing.py, tlm_adjoint/hessian_optimization.py, tlm_adjoint/tlm_adjoint.py
Also
- Remove extra copy of binomial checkpointing references, update `CheckpointStorage` dosctring
- Minor fix to `CheckpointStorage.finalize`
=> Buffer loaded forward restart data in the checkpoint storage

tlm_adjoint/tlm_adjoint.py
Also remove `EquationManager.find_initial_condition`.
=> Remove deprecated Control class

tlm_adjoint/firedrake/backend_overrides.py
See https://github.com/firedrakeproject/firedrake/issues/2555
=> Firedrake backend: Do not allow the Jacobian or RHS to depend on the previous value of the solution in linear variational problems

tlm_adjoint/fenics/backend_code_generator_interface.py
Updates the ghost.
Resolves #188
=> FEniCS backend: Add apply call after matrix multiplication in matrix_multiply

tests/fenics/test_manager.py, tests/firedrake/test_manager.py, tests/numpy/test_manager.py, tlm_adjoint/tlm_adjoint.py
Also add a test for each backend.
Resolves #190
=> Fix TLM annotation control

tests/firedrake/test_interface.py, tlm_adjoint/firedrake/backend_interface.py
=> Firedrake backend: Fix alias data attached to the result from Function.sub

docs/manual.tex, tests/fenics/test_minimize.py, tests/firedrake/test_minimize.py, tlm_adjoint/optimization.py
Also
- Remove J0 argument.
- Make some arguments keyword-only.
- Replace an `allgather` with a `gather`.
=> Use a local manager in minimize_scipy

tests/fenics/test_base.py, tests/firedrake/test_base.py, tests/numpy/test_base.py, tlm_adjoint/_code_generator/equations.py, tlm_adjoint/caches.py, tlm_adjoint/equations.py, tlm_adjoint/hessian.py, tlm_adjoint/optimization.py, tlm_adjoint/verification.py
Also remove some unnecessary `function_update_state` calls.
=> Add some extra clearing of caches

tlm_adjoint/tlm_adjoint.py
Prevent two `EquationManager` objects, on a single process, having the same id.
Previously fixed in #200
=> Ensure that EquationManager ids are unique

tests/fenics/test_base.py, tests/firedrake/test_base.py, tests/numpy/test_base.py
Also minor tidying in `setup_test`.
Resolves #181
=> Use WeakValueDictionary in test_leaks, minor tidying in setup_test

tests/firedrake/test_equations.py, tlm_adjoint/_code_generator/equations.py, tlm_adjoint/fenics/backend_code_generator_interface.py, tlm_adjoint/firedrake/backend.py, tlm_adjoint/firedrake/backend_code_generator_interface.py
Can be used to work around #216
=> Firedrake backend: Use transpose interpolation in ExprEvaluation

tlm_adjoint/tlm_adjoint.py
=> Add a defensive copy in EquationManager._write_memory_checkpoint

tlm_adjoint/__init__.py, tlm_adjoint/checkpointing.py, tlm_adjoint/fenics/backend_interface.py, tlm_adjoint/firedrake/backend_interface.py, tlm_adjoint/hessian.py, tlm_adjoint/hessian_optimization.py, tlm_adjoint/numpy/backend_interface.py, tlm_adjoint/overloaded_float.py
Also some minor edits missed in #226
=> Remove backend GaussNewton and CachedGaussNewton classes

tests/firedrake/test_base.py
=> Firedrake backend: Do not disable the garbage collector in tests

docs/source/conf.py, tests/fenics/test_equations.py, tests/firedrake/test_equations.py, tlm_adjoint/_code_generator/equations.py, tlm_adjoint/fenics/backend_code_generator_interface.py, tlm_adjoint/fenics/backend_interface.py, tlm_adjoint/fenics/backend_overrides.py, tlm_adjoint/fenics/fenics_equations.py, tlm_adjoint/firedrake/backend_code_generator_interface.py, tlm_adjoint/firedrake/backend_interface.py, tlm_adjoint/firedrake/firedrake_equations.py, tlm_adjoint/numpy/backend_interface.py, tlm_adjoint/numpy/equations.py
=> API documentation for the FEniCS/Firedrake backends

tests/fenics/test_base.py, tests/fenics/test_models.py, tests/firedrake/test_base.py, tests/firedrake/test_models.py, tests/numpy/test_base.py, tlm_adjoint/fenics/backend_code_generator_interface.py, tlm_adjoint/firedrake/backend_code_generator_interface.py, tlm_adjoint/firedrake/backend_overrides.py, tlm_adjoint/fixed_point.py, tlm_adjoint/tlm_adjoint.py
=> Use dict(...), list(...) etc. in place of copy.copy

docs/source/examples/1_time_independent.ipynb, docs/source/examples/2_verification.ipynb, docs/source/index.rst
=> Add link to GitHub repository on website, note license

ACKNOWLEDGEMENTS, tests/fenics/test_minimize.py, tests/firedrake/test_minimize.py, tlm_adjoint/optimization.py
Supports MPI parallelism and a more general inner product space. A version of the code previously added to [fenics_ice](https://github.com/EdiGlacUQ/fenics_ice).
Currently uses the non-public SciPy `scipy.optimize.linesearch.scalar_search_wolfe1` function for the line search, due to https://github.com/scipy/scipy/issues/13695.
=> L-BFGS implementation

tlm_adjoint/verification.py
=> Remove manager argument from taylor_test

docs/source/conf.py, docs/source/examples/1_time_independent.ipynb, docs/source/examples/2_verification.ipynb, tlm_adjoint/checkpoint_schedules/periodic.py, tlm_adjoint/fenics/fenics_equations.py, tlm_adjoint/firedrake/firedrake_equations.py, tlm_adjoint/numpy/equations.py
=> NumPy backend documentation

tests/fenics/test_manager.py, tests/firedrake/test_manager.py, tests/numpy/test_manager.py, tlm_adjoint/__init__.py, tlm_adjoint/adjoint.py, tlm_adjoint/checkpointing.py, tlm_adjoint/equations.py, tlm_adjoint/instructions.py
An `Instruction` is an `Equation` which solves for no variables, is excluded from activity analyses, and which is used to record actions to be performed during forward and adjoint calculations.
Used to implement `GarbageCollection`, to indicate garbage collection should be performed in forward and adjoint calculations. Useful when instantiating a `FixedPointSolver`.
Also add `EmptyEquation` as an `Instruction` base class, which also solves for no variables but which is included in activity analyses.
=> Add Instruction class

tlm_adjoint/_code_generator/block_system.py, tlm_adjoint/_code_generator/hessian_system.py, tlm_adjoint/cached_hessian.py, tlm_adjoint/checkpointing.py, tlm_adjoint/eigendecomposition.py, tlm_adjoint/interface.py, tlm_adjoint/optimization.py, tlm_adjoint/tlm_adjoint.py
`comm_dup` seems to lead to deadlocks. Switch to `comm_dup_cached`.
=> Remove use of comm_dup

tests/fenics/test_overrides.py, tests/firedrake/test_overrides.py, tlm_adjoint/_code_generator/equations.py, tlm_adjoint/fenics/backend_code_generator_interface.py
Resolves a bug associated with zero elimination when assembling forms with the FEniCS backend.
=> FEniCS backend: Remove dolfin_form

tlm_adjoint/_code_generator/functions.py, tlm_adjoint/fenics/backend_interface.py, tlm_adjoint/firedrake/backend_interface.py, tlm_adjoint/interface.py, tlm_adjoint/numpy/backend_interface.py, tlm_adjoint/overloaded_float.py
=> Use singledispatch for backend callbacks

tlm_adjoint/_code_generator/functions.py
Reverts changes made as part of #305
=> Firedrake backend: Constant no longer needs to inherit from ufl.Coefficient

tlm_adjoint/_code_generator/functions.py
With the latest version of UFL the count is stored per type.
- Update `extract_coefficients` so that the ordering of dependencies is more stable.
- Set the `_counted_class` manually for `Constant` objects.
=> Firedrake backend: Work around errors associated with counts

.github/workflows/test-fenics.yml, .github/workflows/test-firedrake.yml, tlm_adjoint/checkpoint_schedules/schedule.py
=> flake8 fix

examples/numpy/diffusion/diffusion.py, tlm_adjoint/_code_generator/equations.py, tlm_adjoint/equations.py, tlm_adjoint/fenics/fenics_equations.py, tlm_adjoint/firedrake/firedrake_equations.py, tlm_adjoint/overloaded_float.py, tlm_adjoint/tangent_linear.py
Remove use of and deprecate `get_tangent_linear`
Resolves #235
=> Store tangent-linear directions in a TangentLinearMap

tests/fenics/test_caches.py, tests/fenics/test_eigendecomposition.py, tests/fenics/test_equations.py, tests/fenics/test_gauss_newton.py, tests/fenics/test_hessian_system.py, tests/fenics/test_minimize.py, tests/firedrake/test_caches.py, tests/firedrake/test_eigendecomposition.py, tests/firedrake/test_equations.py, tests/firedrake/test_gauss_newton.py, tests/firedrake/test_hessian_system.py, tests/firedrake/test_minimize.py, tlm_adjoint/_code_generator/equations.py, tlm_adjoint/fenics/backend_code_generator_interface.py, tlm_adjoint/fenics/backend_overrides.py, tlm_adjoint/firedrake/backend_code_generator_interface.py
=> FEniCS/Firedrake backends: Remove use of and deprecate function_vector

tests/fenics/test_minimize.py, tests/firedrake/test_minimize.py, tlm_adjoint/_code_generator/block_system.py, tlm_adjoint/eigendecomposition.py, tlm_adjoint/optimization.py
=> Interface with PETSc TAO for functional minimization

tlm_adjoint/_code_generator/caches.py, tlm_adjoint/_code_generator/equations.py, tlm_adjoint/_code_generator/functions.py, tlm_adjoint/cached_hessian.py, tlm_adjoint/equation.py, tlm_adjoint/equations.py, tlm_adjoint/fenics/backend_code_generator_interface.py, tlm_adjoint/fenics/backend_interface.py, tlm_adjoint/fenics/fenics_equations.py, tlm_adjoint/firedrake/backend_code_generator_interface.py, tlm_adjoint/firedrake/backend_interface.py, tlm_adjoint/firedrake/firedrake_equations.py, tlm_adjoint/fixed_point.py, tlm_adjoint/functional.py, tlm_adjoint/linear_equation.py, tlm_adjoint/manager.py, tlm_adjoint/numpy/backend_interface.py, tlm_adjoint/numpy/equations.py, tlm_adjoint/tangent_linear.py, tlm_adjoint/tlm_adjoint.py
=> Remove most deprecated code

tests/fenics/test_minimize.py, tests/firedrake/test_minimize.py, tlm_adjoint/optimization.py
Also in the TAO interface, allocate `dm` in `Hessian.mult` instead of the `Hessian` constructor.
=> Supply hessp to scipy.optimize.minimize

docs/source/conf.py, tests/fenics/test_eigendecomposition.py, tests/fenics/test_equations.py, tests/firedrake/test_eigendecomposition.py, tests/firedrake/test_equations.py, tests/numpy/test_base.py, tlm_adjoint/_code_generator/block_system.py, tlm_adjoint/_code_generator/caches.py, tlm_adjoint/_code_generator/equations.py, tlm_adjoint/_code_generator/functions.py, tlm_adjoint/checkpoint_schedules/binomial.py, tlm_adjoint/checkpoint_schedules/mixed.py, tlm_adjoint/checkpoint_schedules/schedule.py, tlm_adjoint/checkpointing.py, tlm_adjoint/fenics/__init__.py, tlm_adjoint/fenics/backend.py, tlm_adjoint/fenics/fenics_equations.py, tlm_adjoint/firedrake/__init__.py, tlm_adjoint/firedrake/backend.py, tlm_adjoint/firedrake/firedrake_equations.py, tlm_adjoint/functional.py, tlm_adjoint/interface.py, tlm_adjoint/numpy/backend_interface.py, tlm_adjoint/optimization.py, tlm_adjoint/overloaded_float.py, tlm_adjoint/storage.py, tlm_adjoint/verification.py
Also:
- Minor documentation fixes.
- Some updates to NumPy dtypes.
=> Add some use of intersphinx

tests/fenics/test_float.py, tests/firedrake/test_float.py, tests/numpy/test_float.py, tlm_adjoint/overloaded_float.py
=> Bugfix to Float.new

tests/fenics/test_caches.py, tests/firedrake/test_caches.py, tlm_adjoint/_code_generator/functions.py, tlm_adjoint/interface.py
Bugfix to static autodetection.
=> Bugfix to static DirichletBC objects

.github/workflows/test-fenics.yml, .github/workflows/test-firedrake.yml, setup.cfg, tests/base/test_base.py, tests/base/test_equations.py, tests/base/test_float.py, tests/base/test_interface.py, tests/base/test_manager.py, tests/fenics/test_equations.py, tests/fenics/test_float.py, tests/fenics/test_interface.py, tests/fenics/test_manager.py, tests/fenics/test_overrides.py, tests/firedrake/test_equations.py, tests/firedrake/test_float.py, tests/firedrake/test_interface.py, tests/firedrake/test_manager.py, tests/numpy/test_manager.py, tlm_adjoint/adjoint.py, tlm_adjoint/checkpointing.py, tlm_adjoint/equations.py, tlm_adjoint/fenics/backend_overrides.py, tlm_adjoint/instructions.py, tlm_adjoint/overloaded_float.py, tlm_adjoint/tlm_adjoint.py
=> Add backend independent tests

tlm_adjoint/adjoint.py, tlm_adjoint/cached_hessian.py, tlm_adjoint/caches.py, tlm_adjoint/eigendecomposition.py, tlm_adjoint/equation.py, tlm_adjoint/equations.py, tlm_adjoint/fixed_point.py, tlm_adjoint/functional.py, tlm_adjoint/hessian.py, tlm_adjoint/interface.py, tlm_adjoint/linear_equation.py, tlm_adjoint/manager.py, tlm_adjoint/optimization.py, tlm_adjoint/overloaded_float.py, tlm_adjoint/storage.py, tlm_adjoint/tangent_linear.py, tlm_adjoint/tlm_adjoint.py, tlm_adjoint/verification.py
Documentation updated for consistency but not reviewed.
=> Edits after reviewing code under tlm_adjoint/*.py

docs/source/examples/4_riesz_maps.ipynb, docs/source/examples/6_custom_operations.ipynb, tests/fenics/test_equations.py, tests/firedrake/test_base.py, tests/firedrake/test_block_system.py, tests/firedrake/test_caches.py, tests/firedrake/test_eigendecomposition.py, tests/firedrake/test_equations.py, tests/firedrake/test_hessian_system.py, tests/firedrake/test_minimize.py, tlm_adjoint/_code_generator/block_system.py, tlm_adjoint/_code_generator/functions.py, tlm_adjoint/_code_generator/hessian_system.py, tlm_adjoint/fenics/backend_interface.py, tlm_adjoint/fenics/backend_overrides.py, tlm_adjoint/firedrake/backend.py, tlm_adjoint/firedrake/backend_code_generator_interface.py, tlm_adjoint/firedrake/backend_interface.py, tlm_adjoint/firedrake/backend_overrides.py, tlm_adjoint/firedrake/firedrake_equations.py
Also adds annotation for FEniCS arity one form assembly. This is inefficient when combined with `add_values=True`.
Closes #372
=> Firedrake backend: Dualspace updates

tests/firedrake/test_equations.py, tlm_adjoint/_code_generator/equations.py, tlm_adjoint/_code_generator/functions.py, tlm_adjoint/fenics/backend_code_generator_interface.py, tlm_adjoint/fenics/backend_interface.py, tlm_adjoint/firedrake/backend_code_generator_interface.py, tlm_adjoint/firedrake/backend_interface.py, tlm_adjoint/interface.py
=> Firedrake backend: Non-scalar transpose interpolation

docs/source/examples/1_time_independent.ipynb, tests/fenics/test_interface.py, tests/firedrake/test_interface.py, tlm_adjoint/_code_generator/functions.py, tlm_adjoint/checkpointing.py, tlm_adjoint/equation.py, tlm_adjoint/fenics/backend_interface.py, tlm_adjoint/firedrake/backend_interface.py, tlm_adjoint/hessian.py, tlm_adjoint/interface.py, tlm_adjoint/jax.py, tlm_adjoint/markers.py, tlm_adjoint/optimization.py, tlm_adjoint/overloaded_float.py, tlm_adjoint/tangent_linear.py, tlm_adjoint/verification.py
=> Remove checkpoint variable flag

tlm_adjoint/adjoint.py, tlm_adjoint/cached_hessian.py, tlm_adjoint/caches.py, tlm_adjoint/checkpointing.py, tlm_adjoint/equation.py, tlm_adjoint/equations.py, tlm_adjoint/fixed_point.py, tlm_adjoint/hessian.py, tlm_adjoint/instructions.py, tlm_adjoint/interface.py, tlm_adjoint/jax.py, tlm_adjoint/linear_equation.py, tlm_adjoint/manager.py, tlm_adjoint/optimization.py, tlm_adjoint/overloaded_float.py, tlm_adjoint/storage.py, tlm_adjoint/tangent_linear.py, tlm_adjoint/tlm_adjoint.py, tlm_adjoint/verification.py
Also some minor API updates
- Change some methods to properties
- Create new `EquationManager` objects in Hessian and optimization code
=> Base: Documentation updates

tests/checkpoint_schedules/test_binomial.py, tests/checkpoint_schedules/test_mixed.py, tests/checkpoint_schedules/test_validity.py, tlm_adjoint/checkpoint_schedules/binomial.py, tlm_adjoint/checkpoint_schedules/h_revolve.py, tlm_adjoint/checkpoint_schedules/memory.py, tlm_adjoint/checkpoint_schedules/mixed.py, tlm_adjoint/checkpoint_schedules/periodic.py, tlm_adjoint/checkpoint_schedules/schedule.py
=> checkpoint_schedules: Documentation updates

docs/source/conf.py, tlm_adjoint/fenics/backend_interface.py, tlm_adjoint/fenics/caches.py, tlm_adjoint/fenics/equations.py, tlm_adjoint/fenics/fenics_equations.py, tlm_adjoint/fenics/functions.py, tlm_adjoint/firedrake/block_system.py, tlm_adjoint/firedrake/caches.py, tlm_adjoint/firedrake/equations.py, tlm_adjoint/firedrake/firedrake_equations.py, tlm_adjoint/firedrake/functions.py, tlm_adjoint/firedrake/hessian_system.py
=> FEniCS/Firedrake backends: Documentation updates

tests/base/test_float.py, tests/base/test_jax.py, tlm_adjoint/jax.py, tlm_adjoint/overloaded_float.py
- Set `real=True` or `complex=True` assumptions for `SymbolicFloat` objects.
- Expand overloading.
- Expand overloading tests.
- Check for valid data types in `FloatSpace` and `VectorSpace`.
=> `SymbolicFloat` updates

tests/firedrake/test_overrides.py, tlm_adjoint/firedrake/backend_overrides.py
=> Firedrake backend: Function in-place operators

tlm_adjoint/interface.py, tlm_adjoint/jax.py, tlm_adjoint/overloaded_float.py, tlm_adjoint/tlm_adjoint.py
I removed these as I thought they weren't needed ...
=> contextmanager fix

tlm_adjoint/firedrake/firedrake_equations.py
=> `ExprAssignment` bugfix for subset assignment

tests/test_base.py, tlm_adjoint/override.py
=> Fix to `override_property` for `fset=None`

tlm_adjoint/equation.py, tlm_adjoint/fixed_point.py, tlm_adjoint/tlm_adjoint.py
Also:
- Move `var_update_state` call in `Equation.adjoint`
- Add extra cache validation checks in `Equation.adjoint` and `Equation.adjoint_cached`
- Remove `J` arguments from `Equation.adjoint` and `Equation.adjoint_cached`
Resolves #451
=> Use `Equation.adjoint` method in `FixedPoint.subtract_adjoint_derivative_actions`

tests/base/test_jax.py, tests/firedrake/test_overrides.py, tlm_adjoint/equations.py, tlm_adjoint/fenics/backend_interface.py, tlm_adjoint/fenics/functions.py, tlm_adjoint/firedrake/backend_interface.py, tlm_adjoint/firedrake/functions.py, tlm_adjoint/interface.py, tlm_adjoint/jax.py, tlm_adjoint/overloaded_float.py
Update `DotProductRHS` and `InnerProductRHS` so that their outputs are scalars.
=> Remove `var_sum` interface function

tests/firedrake/test_equations.py, tlm_adjoint/fenics/functions.py, tlm_adjoint/firedrake/backend_interface.py, tlm_adjoint/firedrake/backend_overrides.py, tlm_adjoint/firedrake/equations.py, tlm_adjoint/firedrake/functions.py
=> Firedrake backend: Handle arity 1 `FormSum` case in `Assembly`

tests/firedrake/test_overrides.py, tlm_adjoint/firedrake/backend_overrides.py
=> Firedrake backend: `Cofunction.assign` annotation

tests/firedrake/test_equations.py, tlm_adjoint/firedrake/backend_code_generator_interface.py, tlm_adjoint/firedrake/backend_overrides.py, tlm_adjoint/firedrake/firedrake_equations.py
Update for interpolation API changes
=> Firedrake API update

tests/firedrake/test_overrides.py, tlm_adjoint/firedrake/backend_overrides.py
=> Firedrake backend: `Cofunction` in-place operator annotation

tlm_adjoint/fenics/equations.py, tlm_adjoint/firedrake/equations.py
=> Minor tidying

tests/firedrake/test_patches.py
=> Firedrake backend: `riesz_representation` tests

tlm_adjoint/fenics/backend_patches.py, tlm_adjoint/patch.py
Double patching is simpler.
Also fix possible bugs in FEniCS `LUSolver.solve` and `KrylovSolver.solve` patches.
=> Remove `pre_call`

tests/firedrake/test_equations.py, tlm_adjoint/firedrake/solve.py
Fix an overlapping boundary conditions corner case.
Also some minor test updates.
=> Firedrake backend: `DirichletBC` differentiation bugfix

tests/firedrake/test_equations.py, tlm_adjoint/firedrake/solve.py
Reverts tlm-adjoint/tlm_adjoint#510
=> Revert "Firedrake backend: `DirichletBC` differentiation bugfix"

tests/fenics/test_patches.py, tests/firedrake/test_interface.py, tests/firedrake/test_patches.py, tlm_adjoint/firedrake/backend_patches.py
=> Firedrake backend: Add missing `Cofunction` patches

tlm_adjoint/equation.py, tlm_adjoint/fenics/caches.py, tlm_adjoint/firedrake/backend_interface.py, tlm_adjoint/firedrake/caches.py, tlm_adjoint/interface.py
=> Expand use of variable state locking

tests/firedrake/test_patches.py, tlm_adjoint/fenics/solve.py, tlm_adjoint/firedrake/solve.py
A `LinearSolver` lacks the required `appctx`, so for matfree solves fall back to calling `solve` directly.
=> Firedrake backend: matfree

tlm_adjoint/fenics/expr.py, tlm_adjoint/firedrake/expr.py
=> Firedrake backend: Handle `Coargument` case in `_derivative`

docs/source/dependencies.rst, tests/fenics/test_minimize.py, tlm_adjoint/optimization.py, tlm_adjoint/petsc.py
=> Use TAO for the L-BFGS line search

tlm_adjoint/optimization.py
`scipy.optimize.minimize` is called only on the root process, with other processes controlled via `bcast`s. Add defensive comm duplication so that a new communicator is used on each call.
=> Add a defensive comm duplication in `minimize_scipy`

docs/source/conf.py, tlm_adjoint/alias.py, tlm_adjoint/overloaded_float.py
Minor fixes/tidying
Closes #537
=> Minor updates

tests/firedrake/test_patches.py, tlm_adjoint/firedrake/backend_interface.py, tlm_adjoint/firedrake/backend_patches.py
=> Firedrake backend: Restricted function spaces

tests/firedrake/test_patches.py, tlm_adjoint/firedrake/backend_interface.py, tlm_adjoint/firedrake/backend_patches.py
For older versions of Firedrake without `RestrictedFunctionSpace`.
=> Firedrake backend: Maintain backwards compatibility

tlm_adjoint/checkpoint_schedules/mixed.py
=> Mixed schedule optimization

.github/workflows/test-firedrake.yml, docs/source/acknowledgements.rst, docs/source/conf.py, tests/base/test_torch.py, tests/fenics/test_base.py, tests/firedrake/test_base.py, tests/firedrake/test_torch.py, tlm_adjoint/__init__.py, tlm_adjoint/hessian.py, tlm_adjoint/markers.py, tlm_adjoint/torch.py
Uses the approach of https://arxiv.org/abs/2303.06871v3
=> PyTorch interface

tests/firedrake/test_block_system.py, tlm_adjoint/block_system.py, tlm_adjoint/checkpointing.py, tlm_adjoint/firedrake/block_system.py, tlm_adjoint/optimization.py
e.g. for generating realizations of Gaussian random variables.
=> Matrix function actions using SLEPc

docs/source/examples/8_hessian_uq.ipynb, docs/source/index.rst
=> Hessian-based UQ example

tlm_adjoint/block_system.py
Difficult to trigger, hence no MRE or test
=> Block system: Work around memory leak

tlm_adjoint/interface.py
=> Remove `var_is_checkpointed`

tlm_adjoint/adjoint.py, tlm_adjoint/alias.py, tlm_adjoint/block_system.py, tlm_adjoint/cached_hessian.py, tlm_adjoint/firedrake/block_system.py, tlm_adjoint/hessian.py, tlm_adjoint/hessian_system.py, tlm_adjoint/torch.py
Further progress on #435
Also:
- Remove `Hessian.compute_gradient`.
- Minor refactoring of adjoint right-hand-side classes.
- Fix minor bug (potential memory leak) in `AdjointBlockRHS`.
=> Further use of numpydoc

tlm_adjoint/fenics/backend_patches.py, tlm_adjoint/interface.py
Also some code simplification.
=> Garbage cleanup fix

tlm_adjoint/firedrake/backend_patches.py, tlm_adjoint/firedrake/variables.py
=> Firedrake backend: Raise `NotImplementedError` if mixed primal/dual spaces are encountered

.github/workflows/test-base.yml, .github/workflows/test-fenics.yml, .github/workflows/test-firedrake.yml, tlm_adjoint/firedrake/backend_patches.py
Take the opportunity to run tests using 4 threads
=> Update Firedrake ci

tests/fenics/test_equations.py, tests/firedrake/test_block_system.py, tests/firedrake/test_equations.py, tlm_adjoint/firedrake/backend.py, tlm_adjoint/firedrake/backend_interface.py, tlm_adjoint/firedrake/backend_patches.py, tlm_adjoint/firedrake/expr.py, tlm_adjoint/firedrake/solve.py
Anticipating upcoming Firedrake refactoring
=> Firedrake backend: Remove `LinearSolver` patch

tests/firedrake/test_equations.py, tlm_adjoint/fenics/solve.py, tlm_adjoint/firedrake/parameters.py, tlm_adjoint/firedrake/solve.py
=> Firedrake solves always use a non-zero initial guess
