- python/tlm_adjoint/eigendecomposition.py
At present, memory requirements of eigendecompose scale with NDOFs^2, because functions are allocated for all eigenfunctions, even when only a subset are requested. This commit ensures only the required eigenfuncs/values are allocated.
> Only allocate the requested eigenvectors in eigendecompose.py

- docs/manual.tex
- python/tlm_adjoint_fenics/fenics_equations.py
This solver no longer requires that both fenics functions be defined on the same mesh.
> Enable passing x-coordinates to InterpolationSolver

- examples/fenics/basal_sliding/basal.py
- examples/fenics/basal_sliding/basal_fp.py
- examples/fenics/transport/transport.py
- python/tlm_adjoint/equations.py
- python/tlm_adjoint_fenics/backend_code_generator_interface.py
- python/tlm_adjoint_firedrake/backend.py
- python/tlm_adjoint_firedrake/backend_code_generator_interface.py
- tests/fenics/test_overrides.py
PETSc KSP objects can in principle change the matrix and/or right-hand-side vector. Add some defensive copying to work around this.
> Defensive copying in use of KSPSolve

- python/tlm_adjoint/base_equations.py
- tests/fenics/test_equations.py
- tests/firedrake/test_equations.py
- tests/numpy/test_equations.py
Leads to adjoint inconsistency if the forward solution is non-zero (seen in fenics_ice).
> Add missing zeroing of the forward solution in LinearEquation.forward_solve

- examples/firedrake/basal_sliding/basal.py
- examples/firedrake/basal_sliding/basal_fp.py
Also minor changes to verification tolerances
> Firedrake backend: Reduce solver tolerances in the basal_sliding examples

- docs/manual.tex
- tlm_adjoint/functional.py
- tlm_adjoint/tlm_adjoint.py
Also, do not raise an exception if the tangent-linear variable is not yet in the TangentLinearMap.
> Add optional 'max_depth' argument to EquationManager.tlm and tlm

- docs/manual.tex
- examples/fenics/manual/diffusion_adjoint.py
- examples/fenics/manual/diffusion_adjoint_timestepping.py
- examples/fenics/manual/diffusion_hessian.py
For the (unused) case where dep_index=0
> FEniCS backend: Fix to InteriorAssignmentSolver.adjoint_derivative_action

- tests/fenics/test_base.py
- tests/fenics/test_caches.py
- tests/fenics/test_equations.py
- tests/fenics/test_gauss_newton.py
- tests/fenics/test_manager.py
- tests/firedrake/test_base.py
- tests/firedrake/test_caches.py
- tests/firedrake/test_equations.py
- tests/firedrake/test_gauss_newton.py
- tests/firedrake/test_manager.py
- tests/numpy/test_manager.py
- tlm_adjoint/_code_generator/functions.py
- tlm_adjoint/fenics/backend_interface.py
- tlm_adjoint/firedrake/backend_code_generator_interface.py
- tlm_adjoint/firedrake/backend_interface.py
- tlm_adjoint/numpy/backend_interface.py
These inherit from Constant and Function, as needed by Firedrake assembly. Also remove deprecated Replacement methods, and remove Replacement from `__all__`.
> Add ReplacementConstant and ReplacementFunction classes

- tlm_adjoint/_code_generator/equations.py
- tlm_adjoint/_code_generator/functions.py
- tlm_adjoint/fenics/backend_overrides.py
- tlm_adjoint/firedrake/backend.py
- tlm_adjoint/firedrake/backend_code_generator_interface.py
- tlm_adjoint/firedrake/backend_overrides.py
Also
- Remove custom form binding with the Firedrake backend
- Cache `Zero` elimination
- Apply `Zero` elimination in overridden `assemble` and `assemble_system`
> Firedrake backend: Use ufl.algorithms.strip_terminal_data and ufl.algorithms.replace_terminal_data, if available

- tlm_adjoint/hessian_optimization.py
- tlm_adjoint/tlm_adjoint.py
- Maintain consistency between cp, refs, and data.
- Always copy the initial condition values in `EquationManager.initial_condition`.
- Interface updates, including use of keyword-only arguments.
> Updates to checkpoint storage

- tests/fenics/test_base.py
- tests/fenics/test_caches.py
- tests/fenics/test_equations.py
- tests/fenics/test_examples.py
- tests/fenics/test_manager.py
- tests/fenics/test_minimize.py
- tests/firedrake/test_base.py
- tests/firedrake/test_caches.py
- tests/firedrake/test_equations.py
- tests/firedrake/test_examples.py
- tests/firedrake/test_manager.py
- tests/firedrake/test_minimize.py
- tlm_adjoint/_code_generator/caches.py
- tlm_adjoint/_code_generator/equations.py
- tlm_adjoint/fenics/backend_code_generator_interface.py
- tlm_adjoint/fenics/fenics_equations.py
- tlm_adjoint/firedrake/backend.py
- tlm_adjoint/firedrake/backend_code_generator_interface.py
- tlm_adjoint/firedrake/firedrake_equations.py
Also:
- Remove complex nodes in caching when not in complex mode.
- Add `complex_mode` to backend_code_generator_interfaces module.
> FEniCS/Firedrake backends: Bugfix to matrix-multiplication-based rank 1 form assembly optimization in complex mode

- ACKNOWLEDGEMENTS
- tlm_adjoint/binomial_checkpointing.py
- tlm_adjoint/checkpointing.py
- tlm_adjoint/tlm_adjoint.py
Implement the two-level checkpointing approach described in Pringle et al 2016 and Goldberg et al 2020 (references [5, 6] in ACKNOWLEDGEMENTS).
Also
- Allow an `EquationManager` to be supplied with a custom `CheckpointingManager`.
- `EquationManager.compute_gradient` retains forward data associated with the first block at the end of an adjoint calculation. Make this optional (default disabled) in the `PeriodicDiskCheckpointingManager` and `MultistageCheckpointingManager` classes, and the new `TwoLevelCheckpointingManager` class.
- Allow the original Griewank and Walther 2000 (reference [3] in ACKNOWLEDGEMENTS) schedule to be used with the `MultistageCheckpointingManager` class.
> Two-level checkpointing

- tlm_adjoint/hessian_optimization.py
The forward mode activity analysis means that equation indices can change if the controls change, and then the first order adjoint cache indices are no longer valid.
This is fixed here by clearing the cache if the controls change. This could be optimized by disabling the forward mode activity analysis, or by remapping the cache indices.
> HessianOptimization bugfix: Clear first order adjoint cache if the controls change

- README
- docs/manual.tex
- tests/fenics/test_base.py
- tests/fenics/test_manager.py
- tests/firedrake/test_base.py
- tests/firedrake/test_manager.py
- tests/numpy/test_base.py
- tlm_adjoint/binomial_checkpointing.py
- tlm_adjoint/caches.py
- tlm_adjoint/checkpointing.py
- tlm_adjoint/equations.py
- tlm_adjoint/hessian_optimization.py
- tlm_adjoint/manager.py
- tlm_adjoint/timestepping.py
- tlm_adjoint/tlm_adjoint.py
When performing multiple adjoint calculations associated with the same functional, or with tangent-linears associated with the same functional, the first order adjoint solutions are the same. For example in
```
add_tlm(m, dm)
dJ, ddJ = compute_gradient([J, J.tlm(m, dm)], m)
```
there are three sets of adjoint solutions: a first order adjoint associated with the calculation of `dJ`, and first and second order adjoints associated with the calculation of `ddJ`. The two first order adjoints are equal, allowing caching and reuse between the two adjoint calculations. This PR applies such optimizations automatically.
In some cases this optimization is not needed. For example the calculation above can be replaced with
```
dJ, ddJ = compute_gradient(J.tlm(m, dm), [dm, m])
```
The intended use case …
> Adjoint caching

- docs/manual.tex
- tests/fenics/test_manager.py
- tests/firedrake/test_manager.py
- tests/numpy/test_manager.py
- tlm_adjoint/tlm_adjoint.py
- tlm_adjoint/verification.py
Previously the value stored in the checkpoint storage was used.
This changes the behaviour of `taylor_test` and `taylor_test_tlm_adjoint` in some cases where the control value is modified, but avoids potential bugs associated with the use of data from the checkpoint storage.
Also remove `EquationManager.initial_condition`, and change some lists to tuples
> Use M for control reference value in taylor_test

- tlm_adjoint/tlm_adjoint.py
At the end of `compute_gradient` if `store_adjoint=False` then the adjoint cache should be empty. This PR fixes a corner case where some adjoint variables remained in the cache.
> Ensure that the adjoint cache is cleared when using store_adjoint=False

- docs/manual.tex
- tests/fenics/test_base.py
- tests/firedrake/test_base.py
- tests/numpy/test_base.py
- tlm_adjoint/_code_generator/caches.py
- tlm_adjoint/_code_generator/equations.py
- tlm_adjoint/_code_generator/functions.py
- tlm_adjoint/binomial_checkpointing.py
- tlm_adjoint/caches.py
- tlm_adjoint/checkpointing.py
- tlm_adjoint/eigendecomposition.py
- tlm_adjoint/equations.py
- tlm_adjoint/firedrake/backend_code_generator_interface.py
- tlm_adjoint/firedrake/backend_interface.py
- tlm_adjoint/manager.py
- tlm_adjoint/tlm_adjoint.py
- tlm_adjoint/verification.py
Changes include:
- Allow the `forward` callable to be a function in verification functions
- Backport some fixes/updates from the jrmaddison/H_revolve branch
- API change in `EquationManager.start`, `EquationManager.stop`, `start_manager`, and `stop_manager`, changing the `annotation` argument to `annotate` and making arguments keyword-only
> Minor fixes and tidying

- tlm_adjoint/_code_generator/functions.py
- tlm_adjoint/caches.py
- tlm_adjoint/checkpointing.py
- tlm_adjoint/eigendecomposition.py
- tlm_adjoint/fenics/backend_interface.py
- tlm_adjoint/firedrake/backend_interface.py
- tlm_adjoint/hessian_optimization.py
- tlm_adjoint/interface.py
- tlm_adjoint/numpy/backend_interface.py
- tlm_adjoint/optimization.py
- tlm_adjoint/tlm_adjoint.py
Various driver routines previously made use of duplicate MPI communicators. This PR extends this throughout the rest of the code.
Adds
- `comm_dup`: Unconditionally duplicate the communicator.
- `comm_dup_cached`: Use a cached version of the duplicate communicator if available, otherwise duplicate the communicator and cache the duplicate communicator. Similar in behaviour to the PyOP2 `dup_comm`, but with automatic freeing of the communicator.
- `comm_parent`: Can be used to obtain the communicator passed to `comm_dup` or `comm_dup_cached`.
Weak referencing and finalizers are used to automatically free the duplicate MPI communicators when the Python MPI communicator is destroyed.
`function_comm` and `space_comm` now return duplicate communicators duplicated using `comm_dup_cached`.
There …
> Use duplicate MPI communicators

- tests/firedrake/test_base.py
The most recent version of Firedrake seems to be particularly susceptible to parallel deadlocks. This exposed a bug in the `setup_test` decorator, which did not correctly disable the garbage collector.
This PR fixes this, and also adds some manual garbage collection. This seems to reduce the problem, but may not work around the problem in all cases.
Closes #198
> Work around Firedrake parallel deadlocks

- tlm_adjoint/eigendecomposition.py
- tlm_adjoint/interface.py
Before this PR a cached duplicated MPI communicator was freed on destruction of the associated Python object (see #187). This can cause issues due to non-synchronous object destruction on different processes, and may have been causing deadlocks.
With this PR cached duplicated communicators are freed when the original 'parent' communicator is freed. This moves responsibility for freeing communicators to the calling code.
Some consequences:
- The cached duplicated communicators may be retained for longer than they are needed.
- Cached duplicated communicators cannot be used after the parent communicators are freed. Note that `space_comm` and `function_comm` return cached duplicated communicators, and so these now need to be used with more caution.
- The use cases for `comm_parent` are now …
> Free cached duplicated MPI communicators when the original MPI communicator is freed

- tlm_adjoint/interface.py
- tlm_adjoint/optimization.py
- tlm_adjoint/tlm_adjoint.py
- tlm_adjoint/verification.py
Add `PETSc.garbage_cleanup` calls
- After an adjoint calculation
- When loading checkpoint data
- After running the forward in verification functions
- After running the forward in `minimize_scipy`
> Firedrake backend: Add PETSc.garbage_cleanup calls

- README
- tests/checkpoint_schedules/test_mixed.py
- tests/fenics/test_models.py
- tests/firedrake/test_models.py
- tlm_adjoint/checkpoint_schedules/__init__.py
- tlm_adjoint/checkpoint_schedules/mixed.py
- tlm_adjoint/tlm_adjoint.py
Add a checkpointing schedule optimized for the case of zero storage costs, forward non-reversibility, and in-step adjoint dependency data size equal to forward restart checkpoint data size.
The schedules switch between storing forward restart checkpoints, and storage of non-linear dependency data for use by the adjoint. This generalises the $l = 1$ Runge-Kutta stage CAMS-GEN approach (https://doi.org/10.1016/j.jocs.2022.101913).
> Mixed non-linear dependency / forward restart checkpoint schedule

- tests/checkpoint_schedules/test_binomial.py
- tests/checkpoint_schedules/test_mixed.py
- tests/checkpoint_schedules/test_validity.py
- tests/fenics/test_manager.py
- tests/firedrake/test_manager.py
- tests/numpy/test_manager.py
- tlm_adjoint/checkpoint_schedules/binomial.py
- tlm_adjoint/checkpoint_schedules/h_revolve.py
- tlm_adjoint/checkpoint_schedules/mixed.py
Also
- Add missing data transfer behavior for H-Revolve schedules.
- Do not use disk storage for the single step case in `MixedCheckpointSchedule`.
- Use Numba in `n_advance` for binomial schedules.
> Add further checkpoint schedules tests

- tests/fenics/test_equations.py
A missed argument order update in the FEniCS test_interpolation unit test.
> Fix a DeprecationWarning

- docs/manual.tex
- examples/firedrake/manual/override_adjoint.py
- tests/firedrake/test_overrides.py
- tlm_adjoint/equations.py
- tlm_adjoint/firedrake/backend.py
- tlm_adjoint/firedrake/backend_overrides.py
- tlm_adjoint/manager.py
- tlm_adjoint/tlm_adjoint.py
- tlm_adjoint/verification.py
Automatic annotation / TLM derivation for `interpolate`, `Function.interpolate`, and `Interpolator.interpolate`.
Also add `EquationManager.paused` and `paused_annotation` context managers, which pause and restart the `EquationManager`.
> Firedrake backend: Interpolation annotation

- docs/manual.tex
- tests/fenics/test_equations.py
- tests/firedrake/test_equations.py
- tests/firedrake/test_overrides.py
- tlm_adjoint/_code_generator/equations.py
- tlm_adjoint/firedrake/backend_overrides.py
With the Firedrake backend, add automatic annotation / TLM derivation for rank one assembly via `assemble`.
> Add rank 1 form support to Assembly

- tests/fenics/test_equations.py
- tests/firedrake/test_equations.py
- tlm_adjoint/_code_generator/functions.py
This allocates a `Function`, but prevents spurious derivative elimination.
> FEniCS/Firedrake backend: Switch to a simpler ZeroFunction implementation

- tlm_adjoint/interface.py
> Keep a reference to the original communicator until duplicated communicators are destroyed

- tests/fenics/test_base.py
- tests/fenics/test_equations.py
- tests/firedrake/test_base.py
- tests/firedrake/test_equations.py
- tlm_adjoint/_code_generator/equations.py
- tlm_adjoint/adjoint.py
Use an adjoint initial guess only if it has a matching space type. This is a less restrictive approach than described in #242.
Also:
- Ignore `ZeroConstant` leaks in `test_leaks`. These can be generated and cached by zero elimination.
- Add some extra argument checks in the `EquationSolver` constructor.
- Fix a bug in the construction of the adjoint computational graph, which was not encountered due to the convention of storing the solution first in the tuple of `Equation` dependencies.
Closes #242.
> Use space types to define adjoint initial guesses

- tests/firedrake/test_equations.py
- tlm_adjoint/_code_generator/functions.py
The Firedrake `Function.subfunctions` property uses `type(self)(...)`, and so the `ZeroFunction` constructor needs to be compatible with this usage.
> Firedrake backend: ZeroFunction.subfunctions bugfix

- tests/fenics/test_block_system.py
- tests/fenics/test_eigendecomposition.py
- tests/fenics/test_gauss_newton.py
- tests/fenics/test_hessian_system.py
- tests/firedrake/test_block_system.py
- tests/firedrake/test_eigendecomposition.py
- tests/firedrake/test_gauss_newton.py
- tests/firedrake/test_hessian_system.py
- tlm_adjoint/_code_generator/block_system.py
- tlm_adjoint/_code_generator/hessian_system.py
- tlm_adjoint/alias.py
- tlm_adjoint/cached_hessian.py
- tlm_adjoint/caches.py
- tlm_adjoint/eigendecomposition.py
- tlm_adjoint/fenics/__init__.py
- tlm_adjoint/firedrake/__init__.py
- tlm_adjoint/fixed_point.py
- tlm_adjoint/hessian.py
- tlm_adjoint/interface.py
- tlm_adjoint/manager.py
- tlm_adjoint/optimization.py
- tlm_adjoint/overloaded_float.py
- tlm_adjoint/tlm_adjoint.py
- tlm_adjoint/verification.py
Add functionality for the solution of linear systems defined by Hessian matrices, including partial spectrum preconditioning.
Built on top of a generic interface for solving block linear systems, handling mappings to and from appropriate mixed-spaces. Handles null spaces by constructing non-singular problems associated with consistent singular systems, and which can be constructed so that symmetry and positive semi-definiteness is preserved. This means that PETSc only sees the modified non-singular problem.
Also:
- A simpler interface for solving Hessian eigenproblems.
- Change to space type arguments for `eigendecompose`. The action space type is no longer relative. Breaks API.
- Add some defensive copying when using `minimize_l_bfgs` callable arguments.
- Documentation updates.
> Hessian inverse calculations

- tests/fenics/test_base.py
- tests/firedrake/test_base.py
- tlm_adjoint/_code_generator/block_system.py
- tlm_adjoint/_code_generator/hessian_system.py
- tlm_adjoint/eigendecomposition.py
- tlm_adjoint/interface.py
Fix a memory leak by ensuring that `garbage_cleanup` is called for duplicated communicators.
Also reset `_error_flag` prior to PETSc/SLEPc calls, and fix a documentation typo.
> Fix block system memory leak

- docs/source/examples/1_time_independent.ipynb
- docs/source/examples/3_time_dependent.ipynb
- tests/fenics/test_equations.py
- tests/fenics/test_minimize.py
- tests/fenics/test_models.py
- tests/fenics/test_overrides.py
- tests/firedrake/test_base.py
- tests/firedrake/test_equations.py
- tests/firedrake/test_manager.py
- tests/firedrake/test_models.py
- tests/firedrake/test_overrides.py
- tlm_adjoint/_code_generator/block_system.py
- tlm_adjoint/_code_generator/caches.py
- tlm_adjoint/_code_generator/equations.py
- tlm_adjoint/_code_generator/functions.py
- tlm_adjoint/fenics/backend.py
- tlm_adjoint/fenics/backend_code_generator_interface.py
- tlm_adjoint/fenics/backend_interface.py
- tlm_adjoint/fenics/backend_overrides.py
- tlm_adjoint/firedrake/backend.py
- tlm_adjoint/firedrake/backend_code_generator_interface.py
- tlm_adjoint/firedrake/backend_interface.py
- tlm_adjoint/firedrake/backend_overrides.py
- tlm_adjoint/firedrake/firedrake_equations.py
- tlm_adjoint/interface.py
The Firedrake `Constant` class is no longer a subclass of `ufl.Coefficient`. This means that with the Firedrake backend:
- `Constant` objects no longer appear in the return value of `Form.coefficients` or `ufl.algorithms.extract_coefficients`.
- Expressions and forms cannot be differentiated with respect to `Constant` objects.
However tlm_adjoint allows `Constant` objects to be controls. To work around this:
- The tlm_adjoint `extract_coefficients` function is now used consistently throughout the code. This includes `Constant` objects in the return value.
- The tlm_adjoint `derivative` function is now used consistently throughout the code. This replaces `Constant` objects with `Coefficient` replacements as needed to allow differentiation.
- Similarly the new tlm_adjoint `diff` function is …
> Firedrake backend: Update for new Constant type

- tlm_adjoint/_code_generator/hessian_system.py
- tlm_adjoint/fenics/backend_code_generator_interface.py
- tlm_adjoint/fenics/backend_interface.py
- tlm_adjoint/fenics/backend_overrides.py
- tlm_adjoint/firedrake/backend_code_generator_interface.py
Fix a few cases of
```
fn(arg0=arg0_value, *args, **kwargs)
```
which leads to an error if `args` is not empty. Also remove some unnecessary use `*args` and `**kwargs`.
> *args bugfixes and tidying

- examples/fenics/diffusion/diffusion.py
- examples/firedrake/diffusion/diffusion.py
- tests/firedrake/test_equations.py
- tests/firedrake/test_models.py
- tests/firedrake/test_overrides.py
- tlm_adjoint/_code_generator/equations.py
- tlm_adjoint/_code_generator/functions.py
- tlm_adjoint/_code_generator/hessian_system.py
- tlm_adjoint/cached_hessian.py
- tlm_adjoint/fenics/backend_code_generator_interface.py
- tlm_adjoint/fenics/backend_interface.py
- tlm_adjoint/fenics/backend_overrides.py
- tlm_adjoint/firedrake/backend.py
- tlm_adjoint/firedrake/backend_code_generator_interface.py
- tlm_adjoint/firedrake/backend_interface.py
- tlm_adjoint/firedrake/backend_overrides.py
- tlm_adjoint/firedrake/firedrake_equations.py
- tlm_adjoint/functional.py
- tlm_adjoint/hessian.py
- tlm_adjoint/manager.py
- tlm_adjoint/optimization.py
- tlm_adjoint/overloaded_float.py
- tlm_adjoint/override.py
- tlm_adjoint/tlm_adjoint.py
- tlm_adjoint/verification.py
Apply with the Firedrake backend.
Also remove most use of the optional `manager` argument, and prevent `annotate` and `tlm` keyword arguments overriding the `EquationManager` state.
> Implement a new patch approach for automatic annotation

- docs/source/dependencies.rst
- tests/fenics/test_minimize.py
- tlm_adjoint/firedrake/backend_interface.py
- tlm_adjoint/interface.py
- tlm_adjoint/tlm_adjoint.py
Also drop references for each adjoint model, for each block, in `EquationManager.compute_gradient`.
> Firedrake backend: Call garbage_cleanup on internal PyOP2 communicators

- tests/fenics/test_base.py
- tests/firedrake/test_base.py
- tests/firedrake/test_manager.py
- tests/numpy/test_base.py
- tlm_adjoint/_code_generator/caches.py
- tlm_adjoint/_code_generator/functions.py
`ReplacementConstant` and `ReplacementFunction` have previously inherited from `Constant` and `Function` respectively. The only benefit is that is makes it easy to detect if a `Coefficient` originates e.g. from a `Function` using `isinstance`. However the `Constant` and `Function` constructors were never called when instantiating these objects, and could not be called without defeating the purpose of these `Replacement` subclasses (to define symbolic variables without space allocated for values).
I could only find one case where an `isinstance` check used the previous behaviour, in the matrix action caching optimization. This PR fixes this one case, and updates `ReplacementConstant` and `ReplacementFunction` to no longer inherit from `Constant` and `Function`.
References to `Constant` …
> FEniCS/Firedrake backends: Do not have ReplacementConstant and ReplacementFunction inherit from backend Constant and Function

- tests/checkpoint_schedules/test_binomial.py
- tests/checkpoint_schedules/test_mixed.py
Works around the following behaviour
```
import numpy as np
assert (np.int64(1) == 1) is True  # Fails
```
Here `np.int64(1) == 1` has type `np.bool_`, not `bool`.
> Avoid comparing bools using 'is' in checkpoint schedules tests

- tests/fenics/test_equations.py
- tests/firedrake/test_equations.py
- tlm_adjoint/fenics/fenics_equations.py
Also convert an `Allreduce` to `allreduce`.
Fixes #308
> FEniCS backend: Fix PointInterpolation.forward_solve in parallel

- tests/fenics/test_caches.py
- tests/fenics/test_eigendecomposition.py
- tests/fenics/test_equations.py
- tests/firedrake/test_caches.py
- tests/firedrake/test_eigendecomposition.py
- tests/firedrake/test_equations.py
- tests/firedrake/test_overrides.py
- tests/numpy/test_base.py
- tlm_adjoint/_code_generator/functions.py
- tlm_adjoint/equations.py
- tlm_adjoint/fenics/backend_interface.py
- tlm_adjoint/firedrake/backend_code_generator_interface.py
- tlm_adjoint/firedrake/backend_interface.py
- tlm_adjoint/firedrake/firedrake_equations.py
- tlm_adjoint/interface.py
- tlm_adjoint/numpy/backend_interface.py
- tlm_adjoint/numpy/equations.py
- tlm_adjoint/overloaded_float.py
Avoid casting using dtypes. This, for example, avoids a calculation of the type
```
x = dtype(a) * dtype(b)
```
which in the complex case can be very different from
```
x = dtype(a * b)
```
if `a` and `b` are complex but `dtype` is a real type.
#308 identified while updating the above, fixed separately in #309. Also a few minor complex and parallel updates encountered while updating the above.
> Avoid casting using dtypes

- tlm_adjoint/_code_generator/functions.py
- tlm_adjoint/fenics/backend_interface.py
- tlm_adjoint/firedrake/backend_interface.py
- tlm_adjoint/interface.py
- tlm_adjoint/numpy/backend_interface.py
- tlm_adjoint/overloaded_float.py
Also make the return value writeable.
Leads to more consistent behaviour across backends, and fixes a corner case bug in `MemoryStorage`.
> Always copy values in function_get_values

- tlm_adjoint/fixed_point.py
Catch the 'solution and solution change both equal zero' case by using a non-strict inequality.
> Minor change to fixed-point iteration convergence criteria definition

- tlm_adjoint/firedrake/backend_overrides.py
Fixes an unused case in the local `assign` function
> Firedrake backend: Function_assign corner case bugfix

- tests/firedrake/test_equations.py
- tlm_adjoint/_code_generator/equations.py
- tlm_adjoint/firedrake/firedrake_equations.py
This is less simple that is appears. Really we want to implement.
```
test = TestFunction(adj_x.function_space())
trial = TrialFunction(dep)
residual = dot(test, x - rhs)
dF = derivative(residual, dep, trial)
result = action(adjoint(dF), adj_x)
result = assemble(result)
```
Assuming `dep` is in the primal space, in the above:
- `dot` is used in indicate evaluation of a general antilinear functional in the antidual space represented by `TestFunction(adj_x.function_space())`.
- `assemble` computes degrees of freedom for an antilinear functional by evaluating its input with argument equal, in turn, to each basis function used for the primal space.
The implementation in this PR works, but uses
```
derivative(self._rhs, dep, adj_x)
```
which mixes primal and antidual spaces and so is subtly …
> Firedrake backend: Handle some cases of non-scalar-valued functions in ExprAssignment

- tests/firedrake/test_interface.py
- tlm_adjoint/_code_generator/functions.py
- tlm_adjoint/fenics/backend_interface.py
- tlm_adjoint/firedrake/backend_interface.py
- tlm_adjoint/overloaded_float.py
- Share state values between aliases.
- Do not allow a `Zero` to have its state updated.
Resolves #374
> Changes to state update behaviour

- tests/base/test_float.py
- tests/base/test_jax.py
- tlm_adjoint/_code_generator/functions.py
- tlm_adjoint/fenics/fenics_equations.py
- tlm_adjoint/jax.py
Includes a dtype fix, and fixes a few cases found when checking for empty arrays.
> Parallel bugfix for scalar JAX variables

- tests/checkpoint_schedules/test_binomial.py
- tests/checkpoint_schedules/test_mixed.py
- tests/checkpoint_schedules/test_validity.py
- Check checkpoint schedule max steps while the schedule is running.
- Check that forward restart storage allows the forward to advance sufficiently far when loading checkpoint data.
> Update checkpoint schedules tests

- tests/base/test_base.py
- tests/base/test_float.py
- tests/base/test_jax.py
- tests/fenics/test_base.py
- tests/firedrake/test_base.py
- tlm_adjoint/jax.py
- tlm_adjoint/overloaded_float.py
Use `__array_ufunc__` to implement operator overloading. Leads to much more complete coverage with the JAX interface.
Also:
- Overload `Float.abs`. Use positive sub-gradient at the non-differentiable point.
- Avoid precision errors for small inputs with `Float.expm1`, by defining a custom SymPy `Function`.
- Add `set_default_float_dtype`. Closes #390.
> Improve operator overloading

- tests/firedrake/test_equations.py
- tlm_adjoint/_code_generator/functions.py
- tlm_adjoint/firedrake/firedrake_equations.py
Handle the case `F.assign(c * G)` where `F` and `G` are non-scalar-valued and `c` is an R0 `Function`.
> Firedrake backend: Handle `Function.assign` corner case

- tests/base/test_float.py
- tests/base/test_jax.py
- tlm_adjoint/jax.py
- tlm_adjoint/overloaded_float.py
Copying in the `+` operator might be problematic when annotation is disabled, e.g.
```
start_manager()
J = forward(m)
stop_manager()
dJ = compute_gradient(+J, m)  # always zero
```
However aliasing could be problematic when the annotation is enabled.
To avoid the ambiguity this PR removes `+` overloading.
> Do not overload `+` operator

- tlm_adjoint/adjoint.py
- tlm_adjoint/caches.py
- tlm_adjoint/equation.py
- tlm_adjoint/interface.py
- tlm_adjoint/tangent_linear.py
- tlm_adjoint/tlm_adjoint.py
Could lead to bugs as e.g. `tlm_map[var_replacement(x)]` could differ from `tlm_map[x]`. Added checks in `TangentLinearMap.__contains__`, `TangentLinearMap.__getitem__`, `tlm_key`, and `EquationSolver.var_tlm`.
Also replace some `id` methods with properties, remove use of `weakref.WeakKeyDictionary`, and be slightly more defensive in the use of `weakref.WeakValueDictionary`.
> Do not allow replacement variables to be used to define a tangent-linear

- tests/base/test_equations.py
- tests/base/test_interface.py
- tests/base/test_manager.py
- tests/firedrake/test_interface.py
- tlm_adjoint/adjoint.py
- tlm_adjoint/cached_hessian.py
- tlm_adjoint/checkpointing.py
- tlm_adjoint/eigendecomposition.py
- tlm_adjoint/equation.py
- tlm_adjoint/fenics/backend_interface.py
- tlm_adjoint/fenics/functions.py
- tlm_adjoint/firedrake/backend_interface.py
- tlm_adjoint/firedrake/block_system.py
- tlm_adjoint/firedrake/functions.py
- tlm_adjoint/interface.py
- tlm_adjoint/jax.py
- tlm_adjoint/optimization.py
tlm_adjoint maintains an internal variable 'state'. This state is updated whenever a change to a variable is recorded, which occurs when
- The variable is updated by `Equation.forward` or (as of this PR) `Equation.adjoint`.
- The variable is updated using `var_`-prefixed interface functions.
- Variable updates are recorded in FEniCS/Firedrake overrides.
- With the Firedrake backend (as of this PR): When a `dat_version` changes.
Previously state changes have been used to invalidate cache entries. This PR adds variable state locking, so that attempting to update the state of a locked variable will raise an exception. The primary approach is to use either
- `var_lock_state`: Lock the state of a variable until it is destroyed.
- `StateLockDictionary`: Lock the state of a variable for as long …
> Add variable state locking

- tests/fenics/test_interface.py
- tests/firedrake/test_interface.py
- tlm_adjoint/cached_hessian.py
- tlm_adjoint/fenics/backend_overrides.py
- tlm_adjoint/fenics/equations.py
- tlm_adjoint/fenics/functions.py
- tlm_adjoint/firedrake/backend_interface.py
- tlm_adjoint/firedrake/backend_overrides.py
- tlm_adjoint/firedrake/equations.py
- tlm_adjoint/firedrake/functions.py
- tlm_adjoint/interface.py
- tlm_adjoint/override.py
- For the functional with `CachedHessian` objects.
- For the state with `CachedGaussNewton` objects.
- With `DirichletBC` objects.
The latter in particular leads to an exception being raised if a `DirichletBC`, used by an `EquationSolver`, is modified in a way tlm_adjoint can detect. This could perhaps be replaced by allowing `DirichletBC` objects to be variables (see #422).
> Expand use of variable state locks

- tests/fenics/test_overrides.py
- tests/firedrake/test_overrides.py
- tlm_adjoint/fenics/backend_overrides.py
- tlm_adjoint/fenics/fenics_equations.py
- tlm_adjoint/firedrake/backend_overrides.py
Handles only basic assignment cases, but raises exceptions in unsupported cases.
> FEniCS backend: `Function.interpolate` annotation

- docs/source/examples/0_getting_started.ipynb
- docs/source/index.rst
- readme.rst
The legacy FEniCS backend is already lacking a few newer features. With the FEniCS backend:
- Block system solvers and Hessian solvers have been removed.
- Only special cases of adjoint interpolation are available.
- Variable state locking is much less robust.
- Integration with JAX is untested.
Newer features are very likely to be Firedrake-only.
The FEniCS backend can be retained at least so long as there is a working version in Ubuntu LTS, but this PR removes it as a principal target.
> Remove legacy FEniCS references from the documentation

- tests/base/test_interface.py
- tests/fenics/test_caches.py
- tests/fenics/test_interface.py
- tests/firedrake/test_caches.py
- tests/firedrake/test_interface.py
- tlm_adjoint/caches.py
- tlm_adjoint/equation.py
- tlm_adjoint/fenics/backend_code_generator_interface.py
- tlm_adjoint/fenics/caches.py
- tlm_adjoint/fenics/equations.py
- tlm_adjoint/fenics/fenics_equations.py
- tlm_adjoint/firedrake/backend_code_generator_interface.py
- tlm_adjoint/firedrake/caches.py
- tlm_adjoint/firedrake/equations.py
- tlm_adjoint/firedrake/firedrake_equations.py
- tlm_adjoint/fixed_point.py
- tlm_adjoint/interface.py
1. Values, provided by the `replace_map` when generating cache entries, are now included in the key.
2. Updating the state of a value via `var_update_state` now clears associated cache entries.
3. Validity of cache entries is checked every time before use with extra `var_update_caches` calls. This catches all cache invalidation visible to tlm_adjoint -- which with the Firedrake backend includes any updates to dat versions, even those that do not have associated `var_update_state` calls.
A better alternative to 3 is to make hashing cheap and then simply check the caches every time -- but this needs #183 in order to avoid leaking memory when applying checkpointing.
> Cache improvements

- tlm_adjoint/checkpointing.py
Can lead to unexpected behaviour e.g. with a `Mapping`
> Remove use of `KeyError`

- tests/fenics/test_overrides.py
- tests/firedrake/test_overrides.py
- tlm_adjoint/fenics/__init__.py
- tlm_adjoint/fenics/backend_overrides.py
- tlm_adjoint/fenics/functions.py
- tlm_adjoint/firedrake/__init__.py
- tlm_adjoint/firedrake/backend_interface.py
- tlm_adjoint/firedrake/backend_overrides.py
- tlm_adjoint/firedrake/firedrake_equations.py
- tlm_adjoint/firedrake/functions.py
Handles the case where a `Constant` is initialized using other `Constant`s.
> FEnicS/Firedrake backends: `Constant` constructor annotation

- tests/fenics/test_base.py
- tests/fenics/test_equations.py
- tests/firedrake/test_base.py
- tests/firedrake/test_caches.py
- tests/firedrake/test_equations.py
- tests/test_base.py
- tlm_adjoint/equations.py
- tlm_adjoint/fenics/backend_code_generator_interface.py
- tlm_adjoint/fenics/backend_interface.py
- tlm_adjoint/fenics/caches.py
- tlm_adjoint/fenics/equations.py
- tlm_adjoint/fenics/fenics_equations.py
- tlm_adjoint/fenics/functions.py
- tlm_adjoint/firedrake/backend_code_generator_interface.py
- tlm_adjoint/firedrake/backend_interface.py
- tlm_adjoint/firedrake/backend_overrides.py
- tlm_adjoint/firedrake/caches.py
- tlm_adjoint/firedrake/equations.py
- tlm_adjoint/firedrake/firedrake_equations.py
- tlm_adjoint/firedrake/functions.py
Handles some `FormSum` cases in `EquationSolver`.
There are a number of places where `FormSum` weight dependencies are discarded. The `EquationSolver` constructor currently checks that the weights have no variables as dependencies.
Some possible future steps:
- Handle weight dependencies. This is currently difficult as `ufl.replace` does not update `Constant`s in the weights.
- Check for `FormSum` compatibility elsewhere in the code -- at least checking for use of `Form`s where needed.
- Refactor the `EquationSolver` class. This PR further adds to its complexity.
Closes #445
> Add `FormSum` support to `EquationSolver`

- tests/base/test_jax.py
- tests/fenics/test_equations.py
- tests/firedrake/test_equations.py
- tests/firedrake/test_overrides.py
- tlm_adjoint/checkpointing.py
- tlm_adjoint/fenics/backend_interface.py
- tlm_adjoint/fenics/functions.py
- tlm_adjoint/firedrake/backend_interface.py
- tlm_adjoint/firedrake/functions.py
- tlm_adjoint/instructions.py
- tlm_adjoint/interface.py
- tlm_adjoint/jax.py
- tlm_adjoint/optimization.py
- tlm_adjoint/overloaded_float.py
- tlm_adjoint/tlm_adjoint.py
Also:
- Change `comm_dup_cached` behaviour to prevent duplication of duplicated communicators.
- Other communicator duplication fixes.
> Fix dtype and communicator in `to_float`

- tests/firedrake/test_base.py
- tests/firedrake/test_equations.py
- tests/firedrake/test_overrides.py
- tlm_adjoint/fenics/equations.py
- tlm_adjoint/fenics/fenics_equations.py
- tlm_adjoint/fenics/functions.py
- tlm_adjoint/firedrake/backend_overrides.py
- tlm_adjoint/firedrake/equations.py
- tlm_adjoint/firedrake/firedrake_equations.py
- tlm_adjoint/firedrake/functions.py
Uses approach 3 of #492.
Note that a single `assemble` call may be associated with multiple tape records. This avoids further complicating the `Assembly` class, at the cost of a more complicated computational graph.
Closes #492
> Firedrake backend: `assemble` annotation

- tests/fenics/test_models.py
- tests/firedrake/test_models.py
- tlm_adjoint/equation.py
- tlm_adjoint/fenics/backend_patches.py
- tlm_adjoint/fenics/equations.py
- tlm_adjoint/firedrake/backend_patches.py
- tlm_adjoint/firedrake/equations.py
- tlm_adjoint/functional.py
- tlm_adjoint/jax.py
- tlm_adjoint/optimization.py
- tlm_adjoint/overloaded_float.py
- tlm_adjoint/patch.py
- tlm_adjoint/tlm_adjoint.py
Retained in `EquationSolver.solve` and patched methods. These might later be replaced with use of `paused_manager` etc.
> Remove most usage of `manager`, `annotate`, and `tlm` arguments

- tests/fenics/test_patches.py
- tests/firedrake/test_base.py
- tests/firedrake/test_equations.py
- tlm_adjoint/fenics/backend.py
- tlm_adjoint/fenics/backend_interface.py
- tlm_adjoint/fenics/backend_patches.py
- tlm_adjoint/fenics/caches.py
- tlm_adjoint/fenics/projection.py
- tlm_adjoint/fenics/solve.py
- tlm_adjoint/firedrake/backend_interface.py
- tlm_adjoint/firedrake/backend_patches.py
- tlm_adjoint/firedrake/caches.py
- tlm_adjoint/firedrake/projection.py
- tlm_adjoint/firedrake/solve.py
Previously `Projection` and `LocalProjection` could be supplied with a form, but this is fragile with the introduction of Firedrake `Cofunction`s.
Also:
- Add `LocalEquationSolver`, a superclass of `LocalProjection`.
- FEniCS backend: Annotate `LocalSolver.solve_local`.
- FEniCS backend: Add a state update in `Vector.apply`.
- Firedrake backend: Update test_EquationSolver_DirichletBC.
> Require `Projection` and `LocalProjection` to be supplied with an `Expr`

- tests/firedrake/test_equations.py
- tlm_adjoint/firedrake/solve.py
Replaces #510, which had an incorrect commit message.
Fix an overlapping boundary conditions corner case.
Also some minor test updates.
> Firedrake backend: `DirichletBC` differentiation bugfix

- tests/firedrake/test_caches.py
- tests/firedrake/test_interface.py
- tlm_adjoint/firedrake/backend_patches.py
- tlm_adjoint/firedrake/variables.py
- tlm_adjoint/interface.py
Catches many important cases of extra cache invalidation in #180.
> Firedrake backend: Do not manually update `dat_version`

- tests/fenics/test_equations.py
- tests/firedrake/test_equations.py
- tlm_adjoint/fenics/assembly.py
- tlm_adjoint/fenics/backend.py
- tlm_adjoint/fenics/backend_patches.py
- tlm_adjoint/fenics/caches.py
- tlm_adjoint/fenics/expr.py
- tlm_adjoint/fenics/interpolation.py
- tlm_adjoint/fenics/solve.py
- tlm_adjoint/firedrake/assembly.py
- tlm_adjoint/firedrake/assignment.py
- tlm_adjoint/firedrake/backend.py
- tlm_adjoint/firedrake/backend_interface.py
- tlm_adjoint/firedrake/backend_patches.py
- tlm_adjoint/firedrake/caches.py
- tlm_adjoint/firedrake/expr.py
- tlm_adjoint/firedrake/interpolation.py
- tlm_adjoint/firedrake/solve.py
The usage `ufl.derivative(form, u, argument=du)` with `u` and `du` `Function`s is technically inconsistent with the UFL documentation, but has always worked. However there are now cases with the Firedrake backend involving `Interpolate` where this doesn't seem to work.
This PR uses `action(ufl.derivative(...))` in some cases.
Other changes:
- FEniCS backend: `derivative` now applies `ufl.algorithms.expand_derivatives`.
- FEniCS/Firedrake backends: Remove unnecessary usage of `ufl.algorithms.expand_derivatives`.
- FEniCS/Firedrake backends: Replace most usage of `extract_coefficients` with (the new) `extract_variables`.
- Firedrake backend: Fix a bug in `extract_coefficients`, which missed `ReplacementConstant`s.
- Firedrake backend: Simplification to …
> FEniCS/Firedrake backends: `derivative` improvements

- tlm_adjoint/fenics/caches.py
- tlm_adjoint/firedrake/caches.py
With the Firedrake backend, and the latest UFL, `ufl.UFLException` is no longer defined. Remove the associated try/except when splitting by arity.
Also apply `expand_derivatives` before the `ufl.replace`, and apply `expand_compounds` / `apply_algebra_lowering` before splitting by arity.
> Firedrake backend: Minor UFL API update

- tlm_adjoint/optimization.py
Positive `reason` values do not necessarily indicate success with `TaoLineSearch`.
> Fix reason check in line_search

- tests/firedrake/test_block_system.py
- tlm_adjoint/firedrake/block_system.py
Follow up to #575. We typically want primal space samples. The previous samples are retained via the `WhiteNoiseSampler.dual_sample` method (and this now returns a `Cofunction`).
> Firedrake backend: Apply the Riesz map when drawing white noise samples

- tests/base/test_jax.py
- tests/firedrake/test_equations.py
- tests/firedrake/test_patches.py
- tlm_adjoint/interface.py
- tlm_adjoint/optimization.py
It's not clear where the deadlock is coming from (`PetscCommDuplicate` not being called on all processes during garbage cleanup), but this PR makes the tlm_adjoint `garbage_cleanup` more defensive.
Similarly make the comm finalizer more defensive -- it is now the responsibility of the caller of `comm.Free()` to ensure that `garbage_cleanup(comm)` is called first. This avoids the `delete_fn` calling other MPI routines (see https://docs.open-mpi.org/en/v5.0.x/man-openmpi/man3/MPI_Comm_free.3.html).
> Attempt to work around `garbage_cleanup` deadlock

- tests/firedrake/test_interface.py
Work around https://github.com/firedrakeproject/firedrake/issues/3933 by skipping the affected test.
No practical impact as tlm_adjoint only flags and checks for aliasing, but does not allow aliased variables in taped operations.
> Firedrake backend: Work around Firedrake issue #3933

- tests/firedrake/test_base.py
- tests/firedrake/test_equations.py
- tlm_adjoint/equations.py
- tlm_adjoint/firedrake/interpolation.py
Remove
- (Firedrake backend) `PointInterpolation`. Should be replaced with interpolation using a `VertexOnlyMesh`.
- `MatrixActionRHS`.
Closes #586.
> Remove some unused classes

- tests/fenics/test_equations.py
- tests/fenics/test_patches.py
- tests/firedrake/test_equations.py
- tests/firedrake/test_patches.py
- tlm_adjoint/fenics/backend_patches.py
- tlm_adjoint/fenics/interpolation.py
The FEniCS backend previously handled `Function.assign([linear combination of functions])` using the `ExprInterpolation` class. However this seems fragile in the case of non-continuous functions. This PR removes this case. A better approach for non-variable coefficients is to use `LinearCombination` directly, otherwise a custom `Equation` class will now be needed.
The FEniCS backend `interpolate_expression` now always uses point evaluation via `Expr` for primal `Function` interpolation. This is slow, but I'm not aware of a good general solution with legacy FEniCS. This may also change the behavior for DG functions, but interpolation is ambiguous anyway in this case.
Firedrake note: The Firedrake backend version of `ExprInterpolation` uses Firedrake's much faster approach for interpolation …
> FEniCS backend: assignment and interpolation updates

- tlm_adjoint/fenics/expr.py
- tlm_adjoint/firedrake/expr.py
- tlm_adjoint/overloaded_float.py
Potentially erroneously adds extra non-linear dependencies in some corner cases, e.g. conditionals.
> Remove extraneous lines when gathering non-linear dependencies

- tests/firedrake/test_base.py
- tests/firedrake/test_interface.py
- tlm_adjoint/equation.py
- tlm_adjoint/firedrake/variables.py
- tlm_adjoint/fixed_point.py
- tlm_adjoint/functional.py
- tlm_adjoint/hessian.py
- tlm_adjoint/interface.py
- tlm_adjoint/manager.py
- tlm_adjoint/tlm_adjoint.py
- Remove tests for old `interpolate` and `Interpolator.interpolate`.
- Remove tests for `Constant(..., domain=mesh)`. Code for this is retained, but with a `FutureWarning`, and is now untested.
- Convert all `DeprecationWarning`s to `FutureWarning`s.
> Firedrake backend: Remove tests for deprecated interfaces

- tests/base/test_petsc.py
- tlm_adjoint/block_system.py
- tlm_adjoint/optimization.py
- tlm_adjoint/petsc.py
In the style of Firedrake's behaviour, options dictionaries are now flattened, so e.g.
```
options = {"ksp": {"atol", atol,
"rtol": rtol}}
```
is now automatically flattened in the options dictionary so that it is equivalent to
```
options = {"ksp_atol": atol,
"ksp_rtol": rtol}
```
Applied recursively, with order preserved, and with duplicate keys detected.
> Automatic flattening of `Mapping`s when setting PETSc options

- tlm_adjoint/firedrake/block_system.py
- tlm_adjoint/firedrake/caches.py
- tlm_adjoint/firedrake/parameters.py
- tlm_adjoint/petsc.py
Avoids some cache misses, prevents `ksp_initial_guess_nonzero` being missed when detecting non-zero initial guesses.
> Firedrake backend: Replace solver parameter copying with flattening
